# NOTE: This `0_webui.yml` file is saved in the WebUI, reproduced here only for illustrative purposes
steps:
  # In the WebUI, the `cryptic` launch job _must_ be the first job to run
  - label: ":unlock: demonstrate secrets"
    plugins:
      - staticfloat/cryptic#v2:
          files:
            - ".buildkite/secrets/codesign_key.txt"
          signed_pipelines:
            - pipeline: .buildkite/s3_upload.yml
              signature_file: .buildkite/s3_upload.yml.signature
          unsigned_pipelines:
            - ".buildkite/sandbox_test.yml"
    commands: |
      # Show that we can print out unencrypted secrets
      echo -n "unlocked codesign_key.txt: "
      cat .buildkite/secrets/codesign_key.txt
    agents:
      queue: "juliaecosystem"
      cryptic_capable: "true"
      os: "linux"
