# Only run on agents that are using sandbox.jl
agents:
  queue: "julia"
  sandbox.jl: "true"

steps:
  # Let's launch a job within a sandbox!
  - label: "run code within a sandbox"
    plugins:
      # Install Julia v1.6 to run Sandbox.jl
      - JuliaCI/julia#v1:
          version: 1.6
      - staticfloat/sandbox#v1:
          rootfs_url: "https://github.com/staticfloat/Sandbox.jl/releases/download/julia-python3-77eae3ba/julia-python3.tar.gz"
          rootfs_treehash: "c0f2c53b857189e1c8378bd37c3b620ea4843e07"
          workspaces:
            # Include `/cache` so that `julia` install can properly cache its Julia downloads
            - "/cache:/cache"
    commands: |
      # Make giant file to ensure that we can write out to our workspaces with impunity
      dd if=/dev/zero of=big_fatty bs=1M count=2048
