steps:
  - label: ":s3: upload to cross-job location"
    key: s3-uploader
    plugins:
      - staticfloat/cryptic#v2:
    commands: |
      echo "$$(date)" > date.txt
      buildkite-agent artifact upload date.txt
    env:
      BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "s3://buildkiteartifacts.com/01927275-5307-45c8-8be4-a613b56cd08c/$${BUILDKITE_PIPELINE_ID}/shared"
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    agents:
      queue: "juliaecosystem"
      os: "linux"

  - label: ":s3: read from cross-job location"
    depends_on:
      - "s3-uploader"
    key: s3-downloader
    plugins:
      - staticfloat/cryptic#v2:
    commands: |
      echo "--- buildkite-agent artifact search"
      buildkite-agent artifact search date.txt

      echo "--- buildkite-agent artifact download"
      buildkite-agent artifact download date.txt . --step s3-uploader

      cat date.txt
    env:
      BUILDKITE_ARTIFACT_UPLOAD_DESTINATION: "s3://buildkiteartifacts.com/01927275-5307-45c8-8be4-a613b56cd08c/$${BUILDKITE_PIPELINE_ID}/shared"
    agents:
      queue: "juliaecosystem"
      os: "linux"
