steps:
  - label: ":s3: upload to cross-job location"
    key: s3-uploader
    plugins:
      - staticfloat/cryptic#v2:
    commands: |
      echo "$$(date)" > date.txt
      export BUILDKITE_JOB_ID=00000000-0000-0000-0000-000000000000
      export BUILDKITE_STEP_ID=00000000-0000-0000-0000-000000000000
      buildkite-agent artifact upload date.txt
    env:
      BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET: ${BUILDKITE_PLUGIN_CRYPTIC_BASE64_SIGNED_JOB_ID_SECRET?}
    agents:
      queue: "juliaecosystem"
      os: "linux"

  - label: ":s3: read from cross-job location"
    depends_on:
      - "s3-uploader"
    key: s3-downloader
    plugins:
      - staticfloat/cryptic#v2:
    commands: |
      export BUILDKITE_JOB_ID=00000000-0000-0000-0000-000000000000
      export BUILDKITE_STEP_ID=00000000-0000-0000-0000-000000000000
      echo "--- buildkite-agent artifact search"
      buildkite-agent artifact search date.txt

      echo "--- buildkite-agent artifact download"
      buildkite-agent artifact download date.txt . --step s3-uploader

      cat date.txt
    agents:
      queue: "juliaecosystem"
      os: "linux"
